# Generated by Django 4.2.6 on 2024-01-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bollard_streak', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrystreak',
            options={'managed': False},
        ),
    ]
